name: Lighthouse CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Serve app
        run: npx http-server ./dist/sakai-ng -p 4200 &

      - name: Run Lighthouse CI
        run: npm run lighthouse
