// <auto-generated />
using System;
using Backend.Workflow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Backend.Workflow.WorkflowNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_creation");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lu");

                    b.Property<string>("Lien")
                        .HasColumnType("TEXT")
                        .HasColumnName("lien");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("PlanningId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("planning_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_lecture");

                    b.Property<string>("Titre")
                        .HasColumnType("TEXT")
                        .HasColumnName("titre");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Workflow.WorkflowConfigDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SuperAdminFinalRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowConfigs");
                });

            modelBuilder.Entity("Backend.Workflow.WorkflowConfigEtapeDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasDefaultValue("")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleValidateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValidateurSpecifiqueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DelaiMaxHeures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinalApproval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowConfigId");

                    b.ToTable("WorkflowConfigEtapes");
                });

            modelBuilder.Entity("Backend.Workflow.WorkflowConfigEtapeDb", b =>
                {
                    b.HasOne("Backend.Workflow.WorkflowConfigDb", "Config")
                        .WithMany("Etapes")
                        .HasForeignKey("WorkflowConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("Backend.Workflow.WorkflowConfigDb", b =>
                {
                    b.Navigation("Etapes");
                });
#pragma warning restore 612, 618
        }
    }
}
